extends:
    [
        'stylelint-config-standard',
        'stylelint-config-prettier',
        'stylelint-prettier/recommended',
    ]


"lint-staged": {
  "*.{js,vue}": [
    "vue-cli-service lint"
  ],
  "*.{less,vue}": [
    "stylelint --allow-empty-input"
  ]
}